name: Java and Mysql Intergration Tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
        mysql:
            image: mysql:5.5
            env:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
                MYSQL_DATABASE: core
            ports:
                - 3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start MYSQL Server
        run: sudo service mysql start
      - name: Test MYSQL
        run: mysql --port 3306 -u root -e 'CREATE DATABASE IF NOT EXISTS core;'
      - name: Unit Tests
        run: mvn test -E -B
